services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    depends_on:
      - tempo

  tempo:
    image: oven/bun:latest
    container_name: tempo
    volumes:
      - ./scripts/proxy.js:/app/proxy.js
    working_dir: /app
    command: bun run proxy.js
    ports:
      - '3200:3200'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  default:
