name: Release Check

on:
  push:
    branches:
      - main

permissions:
  contents: write # needed to create tags/releases

jobs:
  release-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important, we need full history to tag properly

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run release detect
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Being explicit here as we want to avoid any dry run
          CI: true
        run: bun run ./scripts/release-detect.js
